table DimCurrency
	lineageTag: 37aa2be1-6f97-4e07-b35c-e52da959f209

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: 0c216639-b523-46ea-889c-6e0c47550f4a
		summarizeBy: none
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column CurrencyAlternateKey
		dataType: string
		lineageTag: 7ed811e3-e82c-46f2-a816-d2981136fbd8
		summarizeBy: none
		sourceColumn: CurrencyAlternateKey

		annotation SummarizationSetBy = Automatic

	column CurrencyName
		dataType: string
		lineageTag: 8a6cae96-6725-48f5-bd24-91e776ef3ef6
		summarizeBy: none
		sourceColumn: CurrencyName

		annotation SummarizationSetBy = Automatic

	partition DimCurrency = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\manoj.c\Desktop\PowerBI\PowerBI-2\DimCurrency.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Use First Row as Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Change Type" = Table.TransformColumnTypes(#"Use First Row as Headers",{{"CurrencyKey", Int64.Type}, {"CurrencyAlternateKey", type text}, {"CurrencyName", type text}})
				in
				    #"Change Type"

	annotation PBI_ResultType = Table

