table DimProduct
	lineageTag: 9394fbe2-b618-4471-87b0-3294417c86a9

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: fd0a42ec-0527-43fe-b958-550e2e83480a
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductAlternateKey
		dataType: string
		lineageTag: 944b2bc7-845a-4e26-b93f-f5f7aa02525b
		summarizeBy: none
		sourceColumn: ProductAlternateKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryKey
		dataType: string
		lineageTag: 78743ddb-a233-4f1f-8533-eea5c2734e3d
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column SizeUnitMeasureCode
		dataType: string
		lineageTag: 100d3f09-d542-41b1-8597-3809bc34673f
		summarizeBy: none
		sourceColumn: SizeUnitMeasureCode

		annotation SummarizationSetBy = Automatic

	column EnglishProductName
		dataType: string
		lineageTag: 4950abbc-ecf2-4e59-931e-c9c5acaab8e2
		summarizeBy: none
		sourceColumn: EnglishProductName

		annotation SummarizationSetBy = Automatic

	column EnglishDescription
		dataType: string
		lineageTag: 7e0ed7e1-a137-4c08-94e5-d4c1b36ab2b5
		summarizeBy: none
		sourceColumn: EnglishDescription

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 21db388c-ff85-41d6-8569-870b730e2899
		summarizeBy: none
		sourceColumn: StartDate

		variation Variation
			isDefault
			relationship: 8c8b32b5-d0ec-40a8-93d8-e23b43136851
			defaultHierarchy: LocalDateTable_32c44a1f-e10e-4459-b26b-3c42f84a8aea.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column EndDate
		dataType: string
		lineageTag: 12d809c3-d455-4b14-9636-a937a6408199
		summarizeBy: none
		sourceColumn: EndDate

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: fe7da8b6-6bf2-4a12-9780-54b069445aa8
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: de602179-13f6-4dca-bede-c0fe6fde7dbd
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column Size
		dataType: string
		lineageTag: ab6cdc4d-9245-4f1a-b252-6cf16c9d3a69
		summarizeBy: none
		sourceColumn: Size

		annotation SummarizationSetBy = Automatic

	column Class
		dataType: string
		lineageTag: 0ed0b822-513d-444f-ae9e-cff244caa717
		summarizeBy: none
		sourceColumn: Class

		annotation SummarizationSetBy = Automatic

	column Style
		dataType: string
		lineageTag: be12a9b3-5349-489a-8228-0702448bb097
		summarizeBy: none
		sourceColumn: Style

		annotation SummarizationSetBy = Automatic

	column ModelName
		dataType: string
		lineageTag: 75a442d6-c3b4-4b84-9580-b1cf24648045
		summarizeBy: none
		sourceColumn: ModelName

		annotation SummarizationSetBy = Automatic

	partition DimProduct = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\manoj.c\Desktop\PowerBI\PowerBI-2\DimProduct.csv"),[Delimiter=",", Columns=36, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Use First Row as Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Change Type" = Table.TransformColumnTypes(#"Use First Row as Headers",{{"ProductKey", Int64.Type}, {"ProductAlternateKey", type text}, {"ProductSubcategoryKey", type text}, {"WeightUnitMeasureCode", type text}, {"SizeUnitMeasureCode", type text}, {"EnglishProductName", type text}, {"SpanishProductName", type text}, {"FrenchProductName", type text}, {"StandardCost", type text}, {"FinishedGoodsFlag", Int64.Type}, {"Color", type text}, {"SafetyStockLevel", Int64.Type}, {"ReorderPoint", Int64.Type}, {"ListPrice", type text}, {"Size", type text}, {"SizeRange", type text}, {"Weight", type text}, {"DaysToManufacture", Int64.Type}, {"ProductLine", type text}, {"DealerPrice", type text}, {"Class", type text}, {"Style", type text}, {"ModelName", type text}, {"LargePhoto", type text}, {"EnglishDescription", type text}, {"FrenchDescription", type text}, {"ChineseDescription", type text}, {"ArabicDescription", type text}, {"HebrewDescription", type text}, {"ThaiDescription", type text}, {"GermanDescription", type text}, {"JapaneseDescription", type text}, {"TurkishDescription", type text}, {"StartDate", type datetime}, {"EndDate", type text}, {"Status", type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Change Type",{"ProductKey", "ProductAlternateKey", "ProductSubcategoryKey", "SizeUnitMeasureCode", "EnglishProductName", "Color", "Size", "Class", "Style", "ModelName", "EnglishDescription", "StartDate", "EndDate", "Status"})
				in
				    #"Removed Other Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

