table FactInternetSales
	lineageTag: e1e6b413-ad82-4249-8b30-0f9f8e03769d

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 1d0ce9b3-71a9-4bef-b9b3-48dcc9ffb5c8
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		formatString: 0
		lineageTag: 3339a600-33e9-4200-82c0-9d07f6892952
		summarizeBy: count
		sourceColumn: OrderDateKey

		annotation SummarizationSetBy = Automatic

	column ShipDateKey
		dataType: int64
		formatString: 0
		lineageTag: 675bea1b-e532-4c7a-a367-47cebeeab6b5
		summarizeBy: count
		sourceColumn: ShipDateKey

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 421ff4f1-e887-4e9b-bde3-b4b82ff42d4a
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column PromotionKey
		dataType: int64
		formatString: 0
		lineageTag: 5feef5ee-2430-4e23-bf65-1d85da8bcb86
		summarizeBy: count
		sourceColumn: PromotionKey

		annotation SummarizationSetBy = Automatic

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: 7c7b3d19-454f-40e9-a638-342c97bbe7fb
		summarizeBy: none
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: 4df46927-38a9-4932-a5b8-b69188e8cc06
		summarizeBy: count
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column SalesOrderNumber
		dataType: string
		lineageTag: eccd267d-5496-4630-8727-5390ac9e8b05
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column SalesOrderLineNumber
		dataType: int64
		formatString: 0
		lineageTag: 05d8df36-26f2-4a42-84dd-0a01ea158325
		summarizeBy: sum
		sourceColumn: SalesOrderLineNumber

		annotation SummarizationSetBy = Automatic

	column RevisionNumber
		dataType: int64
		formatString: 0
		lineageTag: b6e0e00c-396e-4fc3-b3cd-2618742ae6b0
		summarizeBy: sum
		sourceColumn: RevisionNumber

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: 7a9c95e7-2d7b-4333-b38a-92235db51f7f
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: string
		lineageTag: 93379bfc-37d5-4c03-a4fc-739ce91ceefe
		summarizeBy: none
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

	column UnitPriceDiscountPct
		dataType: int64
		formatString: 0
		lineageTag: ef742811-fe9b-4f2e-b613-87af30d2bfd2
		summarizeBy: sum
		sourceColumn: UnitPriceDiscountPct

		annotation SummarizationSetBy = Automatic

	column SalesAmount
		dataType: double
		lineageTag: 0681f4d8-c011-46dc-878d-53588e2973ca
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TaxAmt
		dataType: double
		lineageTag: 5560d480-4652-4c93-9cae-9cbf1074b48e
		summarizeBy: sum
		sourceColumn: TaxAmt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderDate
		dataType: dateTime
		formatString: General Date
		lineageTag: f2ec62b0-facc-4d85-8245-9c9c95b7824c
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

	column ShipDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 83794f7b-67d9-4d18-8b54-19aa96b29556
		summarizeBy: none
		sourceColumn: ShipDate

		variation Variation
			isDefault
			relationship: 9ab941fd-027f-43ef-8e0b-225f1646c1e5
			defaultHierarchy: LocalDateTable_de2fa389-2f2d-4273-a510-b0aca50e7a7b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition FactInternetSales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\manoj.c\Desktop\PowerBI\PowerBI-2\FactInternetSales.csv"),[Delimiter=",", Columns=26, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Use First Row as Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Change Type" = Table.TransformColumnTypes(#"Use First Row as Headers",{{"ProductKey", Int64.Type}, {"OrderDateKey", Int64.Type}, {"DueDateKey", Int64.Type}, {"ShipDateKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"PromotionKey", Int64.Type}, {"CurrencyKey", Int64.Type}, {"SalesTerritoryKey", Int64.Type}, {"SalesOrderNumber", type text}, {"SalesOrderLineNumber", Int64.Type}, {"RevisionNumber", Int64.Type}, {"OrderQuantity", Int64.Type}, {"UnitPrice", type text}, {"ExtendedAmount", type text}, {"UnitPriceDiscountPct", Int64.Type}, {"DiscountAmount", Int64.Type}, {"ProductStandardCost", type number}, {"TotalProductCost", type number}, {"SalesAmount", type text}, {"TaxAmt", type number}, {"Freight", type text}, {"CarrierTrackingNumber", type text}, {"CustomerPONumber", type text}, {"OrderDate", type datetime}, {"DueDate", type datetime}, {"ShipDate", type datetime}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Change Type",{"ProductKey", "OrderDateKey", "ShipDateKey", "CustomerKey", "PromotionKey", "CurrencyKey", "SalesTerritoryKey", "SalesOrderNumber", "SalesOrderLineNumber", "RevisionNumber", "OrderQuantity", "UnitPrice", "UnitPriceDiscountPct", "SalesAmount", "TaxAmt", "OrderDate", "ShipDate"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"SalesAmount", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

